#i need to run the mongo db image as conatiner and assign the name of conatiner and network also volume 

version: '3.9'
networks:
  roboshop:
    driver: bridge
volumes:
  mongodb:
  redis:
services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    volumes:
    - type: volume
      source: mongodb
      target: /data/db
      volume:
        nocopy: true
  redis:
    image: redis
    container_name: redis
    volumes:
    - type: volume
      source: redis
      target: /data
      volume: 
         nocopy: true


