#i need to run the mongo db image as conatiner and assign the name of conatiner and network also volume 

version: '3.9'
networks:
  roboshop:
    driver: bridge
volumes:
  mongodb:
  redis:
services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    volumes:
    - type: volume
      source: mongodb
      target: /data/db
      volume:
        nocopy: true
  redis:
    image: redis
    container_name: redis
    volumes:
    - type: volume
      source: redis
      target: /data
      volume: 
         nocopy: true
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  web:
    image: web:v1
    container_name: web
    depends_on:
      - catalogue
      - user
      - cart
  user:
    image: user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  # cart:
  #   image: cart:v1
  #   container_name : cart
  #   depends_on:
  #     - catalogue
  #     - redis
    


