#i need to run the mongo db image as conatiner and assign the name of conatiner and network also volume 

version: '3'
networks:
  roboshop:
    driver: bridge
volumes:
  # docker volume create mongodb
  mongodb:
  redis:
  mysql:
  rabbitmq:
services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    volumes:
    - type: volume
      source: mongodb
      target: /data/db
      volume:
        nocopy: true
  redis:
    image: redis
    containe_name: redis
    volumes:
    - type: volume
      source: redis
      target: /data 
      volume:
        nocopy: true

